services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}              
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data in volumn
      # - ./data/postgres:/var/lib/postgresql/data # Persist data in local directory
    ports:
      - "5432:5432"
volumes:
  postgres_data: